name: Warde Stock Sync

on:
  schedule:
    # every 30 minutes
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install puppeteer node-fetch form-data
      - name: Run scraper
        run: node sync.js
        env:
          CI: true
