# .github/workflows/sync.yml
name: Fabric Stock Sync

# manually or every 5 minutes
on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  sync-stock:
    runs-on: ubuntu-latest

    steps:
      # 1) Grab your code
      - uses: actions/checkout@v3

      # 2) Set up Node 18
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3) Bootstrap npm (creates package.json)
      - name: Init npm
        run: npm init -y

      # 4) Install the modules your sync.js requires
      - name: Install dependencies
        run: npm install puppeteer node-fetch jsdom axios

      # 5) Run the scraper, passing in your WP creds
      - name: Run stock sync
        env:
          WP_SITE: ${{ secrets.WP_SITE }}
          WP_USER: ${{ secrets.WP_USER }}
          WP_PASS: ${{ secrets.WP_PASS }}
        run: node sync.js
