name: Fabric Stock Sync

# run every 5 minutes + manual dispatch
on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  sync-stock:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Init npm & mark CommonJS
        run: |
          npm init -y
          # no "type=module" so we stay CommonJS

      - name: Install dependencies
        run: npm install puppeteer node-fetch axios

      - name: Run stock sync
        env:
          WP_SITE: ${{ secrets.WP_SITE }}
          WP_USER: ${{ secrets.WP_USER }}
          WP_PASS: ${{ secrets.WP_PASS }}
        run: node sync.js
